### ISSUE TITLE
Can you give me "../../../../fuzzing_aux.h" for security research? Thank you.

### ISSUE THREAD

**Issue by purecall** [antonio-morales/FreeRDP_FUZZ#1]
Hello, I am a security research enthusiast, and I am also studying AFL-fuzz and the FreeRDP project recently.I read your article about FreeRDP_FUZZ, and I feel that the idea is very good!
I tried to compile this project according to the idea mentioned in your article, but it finally get an error that "FreeRDP_FUZZ-master/libfreerdp/core/transport.c:57:10: fatal error: '../../../../fuzzing_aux.h' file not found".
I think the file is in your "/home/antonio/Downloads/FreeFuzzing/FreeRDP/extLibs/", so I hope to get this file to reproduce your vulnerability for learning.
Thank you.

**Comment by antonio-morales** [comment]
Hi @purecall!!

I've just uploaded the file. You can find it at https://github.com/antonio-morales/FreeRDP_FUZZ/blob/master/fuzzing_aux.h

Regards

**Comment by purecall** [comment]
@antonio-morales Thank you! I compiled it successfully!
